default:
	make -C source/sp

all:
	make -C source all

libskynet.a:
	make -C  source libskynet.a
	
skynet:
	make -C source skynet
 
testrbm:
	make -C source testrbm

pred:
	make -C source pred

codec:
	make -C source codec

tidy:
	make -C source tidy

clean:
	make -C source clean
